version: "3.2"

services:
    web: 
      build: ./build/nginx/
      ports: 
        - 80:8080
        - "3000:443"
      expose:
        - 80
      links:
        - db
        - phpfpm
      volumes: &appvolumes
        - ./src:/var/www/html/laravel
        - sockdata:/sock
      depends_on:
          - phpfpm
    phpfpm:
      build: ./build/phpfpm/
      volumes: *appvolumes
    db:
      build: ./build/images/mysql/
      ports:
       - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: "userpass"
        MYSQL_USER: "dbuser"
        MYSQL_PASSWORD: "userpass"
        MYSQL_DATABASE: "laravel"

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
        
volumes: 
    sockdata: